### ISSUE TITLE
We need a number of attacks indicator

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#10]
Show in dashboard - True

Number of attacks | 350 | attacks | Any decrease | Baseline: ~275 | <30% increase | >30% increase | Monthly \| Temporary spike like ramadan to be defined | SCO - Security Team | Dashboard
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by meomancer** [comment]
Duplication of https://github.com/kartoza/rir-dashboard/issues/15
