### ISSUE TITLE
Infor panel indicator metadata

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#100]
Place a nice (i) icon as indicated in position 1:

![image](https://user-images.githubusercontent.com/178003/145792418-75cf6c0d-e534-4192-a788-741fa748ab5d.png)

When clicked replace panel contents or show a popup with additional data for layer:

Description:

![image](https://user-images.githubusercontent.com/178003/145792319-35929382-2fec-4401-96e0-61be3b18c7b6.png)

Date range

In future maybe chart showing change in scenario level over time

Number of  records

Aggregator behaviour

Other interesting stats

**Comment by meomancer** [comment]
This has been implemented
We can add new ticket for new feature
