### ISSUE TITLE
We should aggregate the extra values

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#104]
![image](https://user-images.githubusercontent.com/178003/145796712-99f9d4ac-e19a-4048-a531-13c1c364b938.png)

At the next admin level we should see them there too

![image](https://user-images.githubusercontent.com/178003/145797025-a8a1e261-8587-41de-a0a7-185ed4a1d458.png)

**Comment by meomancer** [comment]
This has been implemented
