### ISSUE TITLE
User interaction for indicators

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#116]
![image](https://user-images.githubusercontent.com/178003/146342454-977e6e9f-52fa-4ec7-b76d-652ee823e2c8.png)

Can you use the same interaction metaphor for expanding / shrinking hte traffic lights as we have for the side menu

Also lets get rid of those solid blocks of colour and try circles or squares with the scenario number in it. If we use circles it will feel more like traffic lights maybe?

**Comment by timlinux** [comment]
Also get all fonts to the same size (and same as size in map layers)

**Comment by meomancer** [comment]
This has been fixed
