### ISSUE TITLE
Popup for GIS layers should have header

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#121]
![image](https://user-images.githubusercontent.com/178003/146519530-a1afb941-f5c0-449b-9289-d45327340c55.png)

Can we have the popup header like the one below

![image](https://user-images.githubusercontent.com/178003/146519629-065c3e01-dee1-4c23-a955-d2a66d01b0a2.png)

**Comment by meomancer** [comment]
This has been fixed
