### ISSUE TITLE
Implement API Support for Indicators

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#124]
![image](https://user-images.githubusercontent.com/178003/147918300-923d3f1e-665e-492c-b352-a6c9ed47516b.png)

I think we can explicitly enable API access and not enable by default.
The write API should expose key properties:

* date
* admin code
* value
* extra_values as a list

The read api could expose the same except for date and then take the date as a filter to restrict the returned data to one time step

As geojson

* admin code
* geometry
* value
* extra_values as a list

The read api could also have a call to get the earliest and latest date available for the indicator.

In theory we could have a harvester and API enabled though it would probably not be advisable.

We could have another  'dummy' harvester which says 'Harvested by external API client' to indicate that the indicator is being populated externally and that forms or other types of harvesting should not be used.

![image](https://user-images.githubusercontent.com/178003/147918815-f8653535-b9ea-430f-a140-319e760e6378.png)

**Comment by meomancer** [comment]
hi @timlinux 
This has been implemented

Here is the example of indicator
https://staging.rir.kartoza.com/somalia/admin/indicator/17/edit

This is how form looks like
![Selection_370](https://user-images.githubusercontent.com/4530905/148168914-f9f2cbd9-8609-4d5c-95c2-32a890a851eb.png)

We can assign this harvester to the indicator
![Selection_368](https://user-images.githubusercontent.com/4530905/148168927-a47a0f58-7946-4318-836a-c77fc7a388e7.png)

It will not show the Data Capture/harvest now buttons
![Selection_369](https://user-images.githubusercontent.com/4530905/148168980-90b30445-dd06-4d7e-ab7e-b2295a7f352a.png)

Here is the example flow of node red to fetch data from http://mapipcissprd.us-east-1.elasticbeanstalk.com/api/public/population-tracking-tool/data/2017,2021/?page=1&limit=20&condition=A&country=SO
and push data to above indicator

[flows.zip](https://github.com/kartoza/rir-dashboard/files/7812401/flows.zip)

**Comment by meomancer** [comment]
Deprecated with https://github.com/kartoza/rir-dashboard/issues/162
