### ISSUE TITLE
New data entered on form does not show on map

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#128]
![image](https://user-images.githubusercontent.com/178003/148943461-aa0182c2-fe91-4efe-b670-bc6c4b582842.png)

I created a new indicator called SAM and  added some data in the form and the map and the map does not show anything

**Comment by meomancer** [comment]
This has been fixed @timlinux 

# Problem
The bug was python eval does not receive "AND" with uppercase

# Solution
Making logic to lower the rule first
