### ISSUE TITLE
We need a meta-harvester

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#129]
Phase 1: work with a spreadsheet or CSV

Setup:
User fills in a form indicating column name for admin area and column names to indicator names for each indicator the sheet contains

Regular use:
User selects the meta harvester by it's name (e.g. Master Sheet Importer) and then uploads a csv or xls.
Meta harvester then pulls out each column of data based on the mappings and inserts into the correct indicator

Phase 2: fetch a spreadsheet from Sharepoint then process as per phase 1

**Comment by timlinux** [comment]
User interface for running the ingestor should be nice and clear like in #135

**Comment by timlinux** [comment]
@AMEENHashmi788 can you please share an example of your latest master sheet here (you can attach) - the one where indicators are in columns rather than tabs

**Comment by AMEENHashmi788** [comment]
Here you go Tim.

**Comment by meomancer** [comment]
hi @AMEENHashmi788 
Could you reshare the file? I can't find the file

Thank you

**Comment by meomancer** [comment]
hi @timlinux 
This has been implemented

Just go to indicator list
There will be "Meta Harvester" button on top-right
![Selection_001](https://user-images.githubusercontent.com/4530905/149452987-4063c1c1-520a-450a-b125-7b18b344fc27.png)

The form
![Selection_002](https://user-images.githubusercontent.com/4530905/149453017-46053704-47eb-46c2-916e-3f061d8fbd4c.png)

When we select file, it will be autopopulated. Currently it is just receive excel
![Selection_003](https://user-images.githubusercontent.com/4530905/149453024-8af97ba2-d55c-4801-8474-3f27e1435097.png)
![Selection_004](https://user-images.githubusercontent.com/4530905/149453084-552386a8-7066-435e-8b27-c2426cbbbed7.png)


When we submit, it will show the detail page
And there will be progress
![Selection_005](https://user-images.githubusercontent.com/4530905/149453095-1dd18e6b-2c95-44e8-abde-f91f514c44ea.png)

When it is done, it will show "FILE" that can be clicked
![Selection_006](https://user-images.githubusercontent.com/4530905/149453107-47b38714-c6ac-4929-8587-7e5c82fa8d76.png)

It will show the result per line on first column
So user can fix it if it is error
![Selection_007](https://user-images.githubusercontent.com/4530905/149453132-b925070d-274a-4dd8-bcdc-9dcd8c75dedb.png)
![Selection_009](https://user-images.githubusercontent.com/4530905/149453143-50334060-5801-414f-86c5-56736c820352.png)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/149506633-61c50f93-0b73-492b-9bdc-407c9a618650.png)

![image](https://user-images.githubusercontent.com/178003/149506840-2f49012f-94bf-494a-a7c9-4013bbb7a7bb.png)

**Comment by meomancer** [comment]
This has been updated @timlinux
