### ISSUE TITLE
Region drill down

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#130]
When user clicks on an area in the map, or on an area name in the scenario  by district list in the side panel, the geography name should be shown according to the level e.g.

District : Adan Yabaal

That item should be at the top of the list and clickable.

When clicked the sidebard should change to show a list of all the indicators grouped by their groups in a long table. At the top of hte table should be the area name and date

District : Adan Yabaal
Date: 22/01/2022
Current scenario: Worsening

When an indicator value is clicked, the sidebar should again change to show at the top:

District : Adan Yabaal
Indicator: SAM
Then a chart showing the indicator values over time.
Then the description of the indicator
Then the colour codes and scenario names and thresholds for the indicator.

The user should be able to navigate back up to the previous panel states with back / forward buttons in the side bar

**Comment by meomancer** [comment]
This has been implemented @timlinux
