### ISSUE TITLE
CSV uploader not clear

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#135]
![Screenshot from 2022-01-12 09-18-15](https://user-images.githubusercontent.com/178003/149099358-e0a20703-a33b-4b90-84e0-ceede319e00d.png)

Change the interaction so that when the upload button is prssed we show a modal with this:

# Upload your data from a CSV

**How to prepare you data:** 

1. Create a spreadsheet with at least 2 colums:

Area Code | Value
----------------|--------
SO1234 | 23

You can add optional extra columns for extra values.

2. Save the document as a comma separated values file in your spreadsheet (File -> Save As -> CSV)  (Irwan use animated gif here)

3. Use the button below to upload the CSV

4. When the upload is complete, this dialog will close and the form will be filled in with your uploaded data

**Comment by meomancer** [comment]
This has been updated @timlinux
