### ISSUE TITLE
We need to add dashboard links to the indicator and indicator group models

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#137]
A simple URL field that we can then point to a metabase or other dashboard from an indicator

In the indicator and indicator group lists we can have a small icon that will take you to the link if it is set,

![image](https://user-images.githubusercontent.com/178003/149508427-66d94bdb-b15a-47e1-9a48-91d085cb2348.png)

On the BI side can you please get an SSL connection set up to the RIR database and construct some views that we can use to create reports. e.g. a view that looks similar to the master list would be good.

**Comment by timlinux** [comment]
To test you can point the covid new cases link to here https://staging.osgs.rir.kartoza.com/bi/public/dashboard/4617443e-1446-4f4b-a8b6-906072d22d6f

See also #152

**Comment by meomancer** [comment]
It has been implemented
Currently it is just link that can be clicked on the circle of the scenario

**Comment by timlinux** [comment]
Tested with GAM - that is super nice thanks @meomancer 

Could you try to make the link an iframe which embeds in the space of the map frame (and a way to hide it again)?

**Comment by meomancer** [comment]
This has been implemented @timlinux
