### ISSUE TITLE
Ingestion for the same date should overwrite records

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#138]
![image](https://user-images.githubusercontent.com/178003/149786483-590c5ca8-6c29-4d3a-80cf-0a6d64ea53eb.png)

![image](https://user-images.githubusercontent.com/178003/149786542-25f10d7b-0581-4a95-a17e-e92e0949de06.png)

**Comment by meomancer** [comment]
it is already overwrite data @timlinux 
i think it is frontend bug
what indicator is it?

**Comment by meomancer** [comment]
hi @timlinux 
This should be fixed
Could you check it?
