### ISSUE TITLE
Meta harvester dealing with text

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#142]
![image](https://user-images.githubusercontent.com/178003/149788328-2dbce8aa-a145-46e2-ac5f-48385f8eb437.png)

E.g. access in our meta sheet has text values:

![image](https://user-images.githubusercontent.com/178003/149788426-97247ec2-9ab9-440a-a4a8-f5b5899c331a.png)

**Comment by meomancer** [comment]
This has been implemented
