### ISSUE TITLE
Formula editor fixes

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#143]
![image](https://user-images.githubusercontent.com/178003/149789545-8991b60a-6e37-48b9-b81e-5adb5f877168.png)

**Comment by meomancer** [comment]
hi @timlinux 
is it "=" is required?
and also for lest we can just use the rigth one without filling x> value like this

![Selection_010](https://user-images.githubusercontent.com/4530905/149882137-3b94daef-19a9-4921-b1e8-76a694044b55.png)
