### ISSUE TITLE
We need a way to download a master sheet

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#146]
cc @AMEENHashmi788 

The user should be able to download a spreadsheet arranged like the master sheet with one column for hte areas, area codes and then for each of the indicators. The sheet should be for the active time step in the animation.

![image](https://user-images.githubusercontent.com/178003/149797335-62db9fad-5717-4074-bb13-1f4911d93984.png)

**Comment by meomancer** [comment]
This has been implemented
