### ISSUE TITLE
global report downloader icon

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#157]
![image](https://user-images.githubusercontent.com/178003/150754214-17ba022b-439f-4a5a-a80b-729d0ba3432b.png)

Can we sort out the alignment and also put an icon like in fba 
![image](https://user-images.githubusercontent.com/178003/150754350-cb4025b5-c144-4dd7-aec4-e70664211d28.png)

**Comment by meomancer** [comment]
This has been implemented
