### ISSUE TITLE
Indicator dashboard not loading

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#158]
![image](https://user-images.githubusercontent.com/178003/150755956-2cd7e580-754b-4600-8ee8-eab6fcd5bb14.png)

![image](https://user-images.githubusercontent.com/178003/150756210-4c4dc4e3-35a4-4808-b118-ec6ba60ca034.png)

**Comment by timlinux** [comment]
Please do a general check of all sidebar interactions to ensure they work

**Comment by meomancer** [comment]
Tested and updated the logic
