### ISSUE TITLE
Last used defaults for uploaders

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#159]
For both the meta and the indicator spreadsheet importers, it will be great if the modal can remember as much of the details from the last session as possible,

![image](https://user-images.githubusercontent.com/178003/150757440-afb29935-575a-4f97-be8b-265abea15e91.png)

The statefulness should be per-indicator so that if they open the same sheet from two different indicator uploaders, it remembers which tabs, columns etc were used for that indicator the last time.

**Comment by meomancer** [comment]
It is impossible to put the file @timlinux 
will just put the others input as the last selection

**Comment by meomancer** [comment]
Updated
The sessions is saved per indicator
So although the file is same, the state is different per indicator and we need to reselect again
