### ISSUE TITLE
Improve label and help for reporting behaviour

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#165]
![image](https://user-images.githubusercontent.com/178003/150761073-eb36246c-5d44-4e35-b96c-b9b5fba79164.png)

Current label is a bit unclear and options can be refined as per diagram below. Can we also embed the diagram as a little help hover or something?

![TimeWindowExplanation](https://user-images.githubusercontent.com/178003/150761226-45cc8ec4-64fc-4e62-be1c-74711a14394e.png)
?

**Comment by meomancer** [comment]
This has been implemented
