### ISSUE TITLE
Help text for value

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#168]
![image](https://user-images.githubusercontent.com/178003/150762235-c853e733-1da2-44bd-9061-9747dccf203e.png)

The values for each scenario can either be:

* Text-based items that map to a number (e.g. 'Worsening' maps to value '1'). In this case, you should use the '=' box below to declare one value per scenario text option. When harvesting from a datasource, that datasource can contain either numeric or text values for the indicator.
* Number based items in a range that map to a scenario (e.g. '1 to 5' maps to 'Worsening').  In this case, use the upper and lower range options individually or together to define the ranges (e.g. 'Worsening' <= 5, 'Better' > 5 and <= 10). When harvesting from a datasource, that datasource can contain ONLY numeric values for the indicator.

**Comment by meomancer** [comment]
This has been implemented
