### ISSUE TITLE
Indicator group and Instance dashboard links

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#171]
![imagem](https://user-images.githubusercontent.com/178003/151159012-ea790c74-cf10-4acc-90a7-6750fe75ec07.png)

These should be managed on the indicator group and instance models and behave the same way as indicator dashboard links.

The instance scenario download button should move over to the left (so we have two circles for that) and use a generic white background

![imagem](https://user-images.githubusercontent.com/178003/151159231-06b0749b-4703-4339-9197-b915f26d5fed.png)

**Comment by meomancer** [comment]
This has been implemented
