### ISSUE TITLE
Create dashboard link model on a per-geography basis

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#173]
could you add a dashboard link to the geography model so that each geometry can have a link that goes to a dashboard just for that geometry

It would work the same way as the other dashboard interactions and be accessible from the popup or side dashboard e.g.

![imagem](https://user-images.githubusercontent.com/178003/151338114-6cced663-ce4d-410d-8761-275c50a8ca58.png)

![imagem](https://user-images.githubusercontent.com/178003/151339381-af35834d-5cdc-41bc-980c-ed6a69bac6fe.png)

cc @AMEENHashmi788

**Comment by meomancer** [comment]
hi @timlinux @AMEENHashmi788 
This has been implemented
Could you try it?

**Comment by AMEENHashmi788** [comment]
Have been through Django and do not see where I can do this task..ie. adding a url that takes me to a powerBi dashboard.

**Comment by AMEENHashmi788** [comment]
Hi Tim/Irwan.

This seems like nice feature to have but this is not what I had requested. This feature would mean someone has to create 74 separate district  dashboards .

I had requested this.
![image](https://user-images.githubusercontent.com/92939482/151692562-65b83d99-cd33-45c0-bec8-d4b462eaaeb1.png)
![PowerBi Links](https://user-images.githubusercontent.com/92939482/151692594-ec2c3b63-fd54-431e-ad8e-c171bc263e59.jpg)

**Comment by timlinux** [comment]
Correct Ameen- I just want to implement it for completeness and consistency. We follow the Principle of Least Surprise which means if the admin user can link dashboards to entities, it should be I uniformly implemented throughout the application.  You other request for the left icons we will deal with separately- see the comments in that issue.

**Comment by timlinux** [comment]
@meomancer The site is currently giving a 502  - will test when you bring it online again.

**Comment by AMEENHashmi788** [comment]
Perfect Tim..thank you.
