### ISSUE TITLE
Aggregate scenario in side panel is blank

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#174]
![imagem](https://user-images.githubusercontent.com/178003/151339631-b165e3d7-f085-4619-ab01-a0058219cf29.png)

I used region rather than district for map and the side panel shows empty when we open the detail view

**Comment by timlinux** [comment]
I clicked again and it works so there is maybe some issue with the background fetch of the dashboard data

**Comment by meomancer** [comment]
Now it shows loading and error when the request is still loading and error
we can revisit this ticket if it is happens
