### ISSUE TITLE
Communicate clearly to the user why indicator checkbox is inactive

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#179]
![image](https://user-images.githubusercontent.com/178003/151772519-f90e1df1-f9c2-44cd-bcea-003c8b8677dd.png)

This should include visual language:

* make the text more faint

Information que's

* Provide a tooltip or other means to tell the user why it cannot be activeated e.g. ' There is no data for <indicator name> for this time period. Select a different time period or ask your administrator to change the aggregation rules to show the last recorded values.'

**Comment by meomancer** [comment]
This has been implemented
