### ISSUE TITLE
Need visual queue to indicate when a group has a checked item

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#180]
![image](https://user-images.githubusercontent.com/178003/151773129-164d6289-ab40-4842-b776-5f60653069f6.png)

Hard to know above that the group contains a checked item

![image](https://user-images.githubusercontent.com/178003/151773226-e1ccc727-f5c6-47ca-82b8-d3e2dc16a6e4.png)

**Comment by meomancer** [comment]
This has been implemented
