### ISSUE TITLE
Need today button on slider

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#181]
So in some cases there may not be recent  date for one indicator and we get wierd things like this:

![image](https://user-images.githubusercontent.com/178003/151774559-ece16699-c21b-4bbf-a0d0-6775845a7813.png)

![image](https://user-images.githubusercontent.com/178003/151774021-f9d3a19f-0e4c-4d3f-9345-b1c4356c7cb6.png)

Can we add the date in the side panel header
Can we list the other indicators but have (no data) after them

**Comment by timlinux** [comment]
Can we also add a button on the slider for dates to let you jump to today

**Comment by meomancer** [comment]
This has been implemented
