### ISSUE TITLE
Create a set up RIR dashboard .md file

### ISSUE THREAD

**Issue by LesegoMohaule** [kartoza/rir-dashboard#191]
Waiting for how to video from @meomancer. Will test instructions and create .md file once I have seen the video.

**Comment by meomancer** [comment]
hi @LesegoMohaule 
the last video is how to setup the RIR
not sure what is missing for the setup documentation

**Comment by LesegoMohaule** [comment]
I am waiting for the video. Currently the dashboard on the localhost is an
empty template. It does not look like the RIR dashboard on
staging.rir.kartoza.com

**Comment by meomancer** [comment]
hi @LesegoMohaule 
I though it is about the RIR setup
If this ticket wants to looks like staging, it is basically input the data on admin

Not sure what the scope of this ticket
CC @timlinux

**Comment by meomancer** [comment]
This has been covered
