### ISSUE TITLE
RIR Architecture Setup

### ISSUE THREAD

**Issue by meomancer** [kartoza/rir-dashboard#35]
![Selection_284](https://user-images.githubusercontent.com/4530905/139186821-bf28917a-7f24-4296-b3f5-76f81e397291.png)

We need to setup the architecture in kubernetes in azure

Problem:
@lucernae needs to prepare geonode + geoserver to be ready for kubernetes
@meomancer needs to prepare rir dashboard to be ready for kubernetes

**Comment by meomancer** [comment]
rir.kartoza.com

**Comment by timlinux** [comment]
superceded by #123
