### ISSUE TITLE
We need a simple way to get the Json endpoint for an indicator

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#4]
![image](https://user-images.githubusercontent.com/178003/137711377-5e7e7085-4109-4786-8ba9-e59b2365c3a7.png)

Something like hetzner UI flow where you hover to get a copy indcator then click a label to add it to your clipboard

![image](https://user-images.githubusercontent.com/178003/137711478-9c7a2b05-cb6b-4a05-ab89-fbb76b57ac7c.png)

**Comment by meomancer** [comment]
This has been implemented

**Comment by meomancer** [comment]
![Selection_023](https://user-images.githubusercontent.com/4530905/154203354-650ffec1-d294-4f6f-b157-1d7f59ed90c2.png)
![Selection_025](https://user-images.githubusercontent.com/4530905/154203360-9510f100-480d-4a28-908c-656b8f1b8faa.png)
