### ISSUE TITLE
Implement map swiper support

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#71]
We need to support map swiping

![image](https://user-images.githubusercontent.com/178003/144014677-48e57899-c77a-4f97-9c7a-9c6bbf655997.png)

The idea is that you can swipe between two indicators to see the contrast between them. There would be two toggle buttons that you can set an indicator as a swiper layer or a background layer. Only one of each can ever be active at a time and also you can have none activated.

![image](https://user-images.githubusercontent.com/178003/144014857-2186a052-6088-48e2-8590-23f499bd87a0.png)

**Comment by meomancer** [comment]
It is fixed for now

**Comment by timlinux** [comment]
We are looking for behaviour like this @meomancer https://openlayers.org/en/latest/examples/layer-swipe.html

So we can have behaviour like github (or our other agri project)

![Peek 2021-12-08 09-31](https://user-images.githubusercontent.com/178003/145184292-7d61e73e-93c9-4c21-aeb7-961b0ef35e6d.gif)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/145184607-ccdf4a81-d3b6-46ba-9986-0c831e3047b1.png)

**Comment by timlinux** [comment]
![2021-12-08_09-47](https://user-images.githubusercontent.com/178003/145187055-9728abca-dbcd-483f-948c-9c7fb41bd06c.png)

Behaviour rules would be

1) When checkin a layer it would set the geog level to the level defined in the indicator e.g. IPC Level for an IPC Layer, District level for people in need.
2) If using the swiper the levels can be set independently
3) invalid levels would be grayed out (regardless of if you are in swipe mode or not)

**Comment by meomancer** [comment]
This has been implemented
