### ISSUE TITLE
R&D workflow for sharepoint docs

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#72]
https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service?tabs=csom

We need to support workflow whereby:

* A spreadsheet is placed in sharepoint.
* We access the sheet via the sharepoint api
* An indicator is established against that sheet
* Indicator harvester does mappings of columns for geography, date, indicator value
* Harvester retrieves data from the sheet at regular intervals

**Comment by meomancer** [comment]
hi @timlinux 
do you think that it is like gdrive?
that we can have download link for the file?
so harvester can just download the file?

**Comment by meomancer** [comment]
This has been implemented
Technically we use onedrive and also create the harvester in form
