### ISSUE TITLE
UI Papercuts

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#83]
![image](https://user-images.githubusercontent.com/178003/145182218-8803bb66-cd68-402d-b7a4-fe70a319fa89.png)
 Put expand button above or increase the space

Create a sense of spatial alighment 
![image](https://user-images.githubusercontent.com/178003/145182561-a55267ed-aeac-4d5c-b8f4-bcc3b6915342.png)

We coudl remove the text "overall scenario" and then move the subtitle up and make the header line up with the dashboard icon.

![image](https://user-images.githubusercontent.com/178003/145182699-f15f3ad8-d169-45ed-9eb6-5692591402a8.png)

Remove padding

![image](https://user-images.githubusercontent.com/178003/145183276-35a2b3b0-3066-469e-9fda-9543ff8fe5fb.png)

![image](https://user-images.githubusercontent.com/178003/145183324-9a5365d2-ed50-4cb5-a1b9-a509efa6bcde.png)

Use aggregate colour styling for indicator when it is collaped (and maybe expanded too?)

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/145185063-0d55d9ea-e37b-4b20-99d6-5737555f0db2.png)

For aggregate colour probably better to use rectangular panel rather than pill button style

**Comment by meomancer** [comment]
Fixed
