### ISSUE TITLE
Make popup have higher z than splitter

### ISSUE THREAD

**Issue by timlinux** [kartoza/rir-dashboard#94]
![image](https://user-images.githubusercontent.com/178003/145789475-730bb6a8-a26b-44db-a983-1b1c9c24722d.png)

**Comment by meomancer** [comment]
it can't be done @timlinux 
because the popup is same element with the map that is same level
If we make the popup higher than the swiper, the swiper will be behind map

To fix this, i need to update the library
Will check it later
